dataset: 'openpose'
joints_to_ign: 
    - -1
joints_to_increase: 
    - 2
    - 5
data_folder: "data"
output_folder: 'smplx_debug'
prior_folder: 'priors'
model_folder: 'data/models'
result_folder: 'results'
gender: "neutral"
model_type: 'smplx'
# Flag for using the GPU
use_cuda: True
float_dtype: "float32"
use_joints_conf: True
use_pca: True
use_hands: True
use_face: True
flat_hand_mean: False
# The number of mixture components for the pose prior
num_gaussians: 8
body_prior_type: 'l2'
left_hand_prior_type: l2
right_hand_prior_type: l2
jaw_prior_type: 'l2'
focal_length: 5000
num_pca_comps: 12
# The constant for the robust loss function
rho: 100
interpenetration: True
df_cone_height: 0.0001
# Upper arms and Spine 2
# Neck and jaw
ign_part_pairs: ["9,16", "9,17", "6,16", "6,17", "1,2", "12,22"]
penalize_outside: True
max_collisions: 128
# LBFGS with line search
optim_type: 'trustncg' 
ftol: -1.0
gtol: 1e-9
lr: 1.0
# Max number of optimization iterations
maxiters: 30
interactive: False
visualize: False
# Relative change in loss value
body_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4e0
    - 4.78e0
    - 4.78e0
shape_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
expr_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
hand_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4
    - 4.78
    - 4.78
jaw_pose_prior_weights:
    # First phase
    - 4.04e03,4.04e04,4.04e04
    # Second phase
    - 4.04e03,4.04e04,4.04e04
    # Third phase
    - 574,5740,5740
    # Fourth phase
    - 47.8,478,478
    # Fifth phase
    - 47.8,478,478
hand_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.2
    - 4.0 
face_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0 
use_vposer: True
vposer_ckpt: "data/vposer_v1_0"
boneorientation_loss: True
init_joints_idxs: [2, 5, 3, 6]
body_boneorientation_pairs: ["1,8", "2,3", "3,4", "5,6", "6,7"]
hand_boneorientation_pairs: ["0,1", "0,5", "0,9", "0,13", "0,17", "1,2","5,6","9,10","13,14","17,18","2,3","6,7","10,11","14,15","18,19","3,4","7,8","11,12","15,16","19,20"]
loss_type: sgnify
symmetry_weight: 3.0e2 #1e3 
body_temp_smooth_weight: 2.5e2 # 2.5e2
hand_temp_smooth_weight: 1.0e1 #1.0e1
coll_loss_weight: 5.0e2
start_opt_stage: 2
scopti_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 1000 #500.0
camera_type: persp
